const express = require('express');
const router = express.Router();
const upload = require('../middleware/upload');
const invitationDataController = require('../controllers/InvitationDataController');

router.post('/', upload.single('image'), invitationDataController.create);
router.get('/', invitationDataController.getAll);
router.get('/:id', invitationDataController.getById);
router.put('/:id', invitationDataController.update);
router.patch('/invitation/:invitation_id/template_section/:template_section_id', upload.single('image'), invitationDataController.patchData);
router.delete('/:id', invitationDataController.delete);
router.get('/invitation/:invitation_id/template_section/:template_section_id', invitationDataController.getByInvitationAndTemplateSection);
router.get('/invitation/:invitation_id', invitationDataController.getAllByInvitationId);
router.post('/image', upload.single('image'), invitationDataController.uploadImage);
router.delete('/image/:image_id', invitationDataController.deleteImage);
router.get(`/public_id/:public_id`, invitationDataController.getDataByPublicId);
router.get(`/rsvp/:rsvp_token`, invitationDataController.getDataByRsvpToken);
router.delete('/delete_repeated_entry/invitation/:invitation_id/template_section/:template_section_id/nano_id/:nano_id', invitationDataController.deleteRepeatedData);
router.patch('/patch_repeated_entry/invitation/:invitation_id/template_section/:template_section_id/nano_id/:nano_id', upload.single('image'), invitationDataController.patchRepeatedEntry);
module.exports = router;